[workspace]
resolver = "2"
members = [
    "crates/mic-message",
    "crates/mic-store",
    "crates/mic-tool",
    "crates/mic-core",
    "crates/mic-provider-openai",
    "crates/mic-tool-shell",
    "crates/mic-tool-fs",
    "crates/mic-tool-web-fetch",
    "crates/mic-gateway",
    "bin/micnext",
]

[workspace.package]
edition = "2021"
