[package]
name = "mic-core"
version = "0.0.0"
edition.workspace = true

[dependencies]
mic-message = { path = "../mic-message" }
mic-store = { path = "../mic-store" }
mic-tool = { path = "../mic-tool" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["rt", "macros"] }
tokio-util = "0.7"
toml = "0.9"
tracing = "0.1"
