[package]
name = "mic-tool-shell"
version = "0.0.0"
edition.workspace = true

[dependencies]
mic-core = { path = "../mic-core" }
mic-message = { path = "../mic-message" }
mic-tool = { path = "../mic-tool" }
nix = { version = "0.30", features = ["signal"] }
schemars = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["process", "time", "io-util"] }
